[build]
builder = "dockerfile"

[deploy]
startCommand = "serve -s dist -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
