[build]
builder = "nixpacks"
buildCommand = "cd website && npm install && npm run build"

[deploy]
startCommand = "cd website && npx serve -s dist -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
